// ThemePresets.js — color palettes for niri-strata.
// Each preset has a dark and light variant with 33 color keys
// matching Theme.colors.* property names.
// scrim, shadow, transparent are fixed (not in presets).

var presets = {
    default: {
        dark: {
            background: "#101418",
            surface: "#101418",
            layer0: "#171c20",
            layer1: "#1d2328",
            layer1Hover: "#283038",
            layer1Active: "#333d45",
            surfaceContainerLowest: "#0b0f12",
            surfaceContainerLow: "#171c20",
            surfaceContainer: "#1d2328",
            surfaceContainerHigh: "#273038",
            surfaceContainerHighest: "#323c45",
            text: "#e2e8ee",
            mutedText: "#bcc7d0",
            subtleText: "#89959f",
            primary: "#9bd4ff",
            primaryText: "#00344f",
            primaryContainer: "#164b68",
            primaryContainerText: "#cce7ff",
            secondary: "#c0c8d2",
            secondaryContainer: "#3f4850",
            secondaryContainerText: "#dce4ec",
            tertiary: "#dbc0ff",
            tertiaryContainer: "#55406f",
            tertiaryContainerText: "#eddcff",
            successColor: "#9ed9b3",
            successContainer: "#1f5234",
            warningColor: "#f3cf7a",
            warningContainer: "#5a471b",
            errorColor: "#ffb4ab",
            errorContainer: "#73342d",
            outline: "#414b54",
            outlineVariant: "#303941"
        },
        light: {
            background: "#f8fafc",
            surface: "#f8fafc",
            layer0: "#f1f5f9",
            layer1: "#e8eef4",
            layer1Hover: "#dbe4ec",
            layer1Active: "#c9d5e0",
            surfaceContainerLowest: "#ffffff",
            surfaceContainerLow: "#f1f5f9",
            surfaceContainer: "#e8eef4",
            surfaceContainerHigh: "#dbe4ec",
            surfaceContainerHighest: "#c9d5e0",
            text: "#1a2330",
            mutedText: "#4a5666",
            subtleText: "#6b7888",
            primary: "#0066a0",
            primaryText: "#ffffff",
            primaryContainer: "#cce7ff",
            primaryContainerText: "#00344f",
            secondary: "#5a6677",
            secondaryContainer: "#dce4ec",
            secondaryContainerText: "#1a2330",
            tertiary: "#7b3fa0",
            tertiaryContainer: "#eddcff",
            tertiaryContainerText: "#2a1a40",
            successColor: "#2a8a4a",
            successContainer: "#d0f0d8",
            warningColor: "#a07b1a",
            warningContainer: "#fef3cd",
            errorColor: "#c0392b",
            errorContainer: "#fadbd8",
            outline: "#aab8c8",
            outlineVariant: "#c4d0dc"
        }
    },
    blue: {
        dark: {
            background: "#0c1419",
            surface: "#0c1419",
            layer0: "#121e26",
            layer1: "#182530",
            layer1Hover: "#1f3340",
            layer1Active: "#284354",
            surfaceContainerLowest: "#080f14",
            surfaceContainerLow: "#121e26",
            surfaceContainer: "#182530",
            surfaceContainerHigh: "#1f3340",
            surfaceContainerHighest: "#284354",
            text: "#ddeaf2",
            mutedText: "#a8bcc9",
            subtleText: "#7d94a3",
            primary: "#42a5f5",
            primaryText: "#001327",
            primaryContainer: "#0d47a1",
            primaryContainerText: "#b3d4ff",
            secondary: "#b8c8d4",
            secondaryContainer: "#3a4a55",
            secondaryContainerText: "#d0e0ec",
            tertiary: "#cfbcff",
            tertiaryContainer: "#4a3a70",
            tertiaryContainerText: "#e4d4ff",
            successColor: "#80d9a0",
            successContainer: "#1a4a30",
            warningColor: "#f0ca6a",
            warningContainer: "#4a3e1a",
            errorColor: "#ffa8a0",
            errorContainer: "#6a2a24",
            outline: "#3a4a55",
            outlineVariant: "#2a3a45"
        },
        light: {
            background: "#f5f9fc",
            surface: "#f5f9fc",
            layer0: "#eaf2f8",
            layer1: "#dde9f2",
            layer1Hover: "#c8dbe8",
            layer1Active: "#b0c8dc",
            surfaceContainerLowest: "#ffffff",
            surfaceContainerLow: "#eaf2f8",
            surfaceContainer: "#dde9f2",
            surfaceContainerHigh: "#c8dbe8",
            surfaceContainerHighest: "#b0c8dc",
            text: "#0c1a28",
            mutedText: "#3a4a5a",
            subtleText: "#5a6b7a",
            primary: "#0d6dbf",
            primaryText: "#ffffff",
            primaryContainer: "#b3d4ff",
            primaryContainerText: "#001327",
            secondary: "#4a5a6a",
            secondaryContainer: "#d0e0ec",
            secondaryContainerText: "#0c1a28",
            tertiary: "#6a3a9a",
            tertiaryContainer: "#e4d4ff",
            tertiaryContainerText: "#22103a",
            successColor: "#1a8a48",
            successContainer: "#c8f0d4",
            warningColor: "#8a6a1a",
            warningContainer: "#fef5d8",
            errorColor: "#b8382a",
            errorContainer: "#fad5d0",
            outline: "#9aabb8",
            outlineVariant: "#bccad6"
        }
    },
    green: {
        dark: {
            background: "#0d1614",
            surface: "#0d1614",
            layer0: "#13201d",
            layer1: "#1a2a26",
            layer1Hover: "#233932",
            layer1Active: "#2e4540",
            surfaceContainerLowest: "#08110f",
            surfaceContainerLow: "#13201d",
            surfaceContainer: "#1a2a26",
            surfaceContainerHigh: "#233932",
            surfaceContainerHighest: "#2e4540",
            text: "#dceee8",
            mutedText: "#a4c4b8",
            subtleText: "#789a8c",
            primary: "#66bb6a",
            primaryText: "#00280a",
            primaryContainer: "#1b5e20",
            primaryContainerText: "#a5d6a7",
            secondary: "#b4ccc4",
            secondaryContainer: "#364a42",
            secondaryContainerText: "#c8e0d8",
            tertiary: "#c4d8ff",
            tertiaryContainer: "#3a4a70",
            tertiaryContainerText: "#d8e4ff",
            successColor: "#80d9a0",
            successContainer: "#1a4a30",
            warningColor: "#f0ca6a",
            warningContainer: "#4a3e1a",
            errorColor: "#ffa8a0",
            errorContainer: "#6a2a24",
            outline: "#364a42",
            outlineVariant: "#263a32"
        },
        light: {
            background: "#f2faf6",
            surface: "#f2faf6",
            layer0: "#e6f5ee",
            layer1: "#d8efe4",
            layer1Hover: "#c4e6d8",
            layer1Active: "#a8d8c4",
            surfaceContainerLowest: "#ffffff",
            surfaceContainerLow: "#e6f5ee",
            surfaceContainer: "#d8efe4",
            surfaceContainerHigh: "#c4e6d8",
            surfaceContainerHighest: "#a8d8c4",
            text: "#0a2018",
            mutedText: "#2a4a3a",
            subtleText: "#4a6a5a",
            primary: "#2e7d32",
            primaryText: "#ffffff",
            primaryContainer: "#a5d6a7",
            primaryContainerText: "#00280a",
            secondary: "#4a6a5a",
            secondaryContainer: "#c8e0d8",
            secondaryContainerText: "#0a2018",
            tertiary: "#3a4a9a",
            tertiaryContainer: "#d8e4ff",
            tertiaryContainerText: "#001a3a",
            successColor: "#1a7a3a",
            successContainer: "#c4f0d4",
            warningColor: "#8a6a1a",
            warningContainer: "#fef5d8",
            errorColor: "#b8382a",
            errorContainer: "#fad5d0",
            outline: "#8ab8a0",
            outlineVariant: "#aecdb8"
        }
    },
    rose: {
        dark: {
            background: "#180d12",
            surface: "#180d12",
            layer0: "#21141a",
            layer1: "#2a1a22",
            layer1Hover: "#3a2430",
            layer1Active: "#483040",
            surfaceContainerLowest: "#12090d",
            surfaceContainerLow: "#21141a",
            surfaceContainer: "#2a1a22",
            surfaceContainerHigh: "#3a2430",
            surfaceContainerHighest: "#483040",
            text: "#f0dce2",
            mutedText: "#c8a8b8",
            subtleText: "#9a7888",
            primary: "#f48fb1",
            primaryText: "#3a0018",
            primaryContainer: "#9c2740",
            primaryContainerText: "#ffd0e0",
            secondary: "#d4bcc4",
            secondaryContainer: "#4a3a42",
            secondaryContainerText: "#e8d0d8",
            tertiary: "#d8c4ff",
            tertiaryContainer: "#4a3a70",
            tertiaryContainerText: "#e8d8ff",
            successColor: "#90d9a8",
            successContainer: "#1a4a30",
            warningColor: "#f0ca6a",
            warningContainer: "#4a3e1a",
            errorColor: "#ffb0a0",
            errorContainer: "#6a2a24",
            outline: "#4a3a42",
            outlineVariant: "#3a2a32"
        },
        light: {
            background: "#fcf2f6",
            surface: "#fcf2f6",
            layer0: "#f8e8ee",
            layer1: "#f0d8e2",
            layer1Hover: "#e4c0d0",
            layer1Active: "#d0a0b8",
            surfaceContainerLowest: "#ffffff",
            surfaceContainerLow: "#f8e8ee",
            surfaceContainer: "#f0d8e2",
            surfaceContainerHigh: "#e4c0d0",
            surfaceContainerHighest: "#d0a0b8",
            text: "#200a14",
            mutedText: "#5a3a4a",
            subtleText: "#7a5a6a",
            primary: "#c04060",
            primaryText: "#ffffff",
            primaryContainer: "#ffd0e0",
            primaryContainerText: "#3a0018",
            secondary: "#6a4a5a",
            secondaryContainer: "#e8d0d8",
            secondaryContainerText: "#200a14",
            tertiary: "#5a3a9a",
            tertiaryContainer: "#e8d8ff",
            tertiaryContainerText: "#1a003a",
            successColor: "#1a7a3a",
            successContainer: "#c4f0d4",
            warningColor: "#8a6a1a",
            warningContainer: "#fef5d8",
            errorColor: "#b8382a",
            errorContainer: "#fad5d0",
            outline: "#b888a0",
            outlineVariant: "#d0a8b8"
        }
    },
    amber: {
        dark: {
            background: "#161008",
            surface: "#161008",
            layer0: "#1f180e",
            layer1: "#281e12",
            layer1Hover: "#382c18",
            layer1Active: "#483a20",
            surfaceContainerLowest: "#100a04",
            surfaceContainerLow: "#1f180e",
            surfaceContainer: "#281e12",
            surfaceContainerHigh: "#382c18",
            surfaceContainerHighest: "#483a20",
            text: "#f0e4d0",
            mutedText: "#c8b894",
            subtleText: "#9a8a68",
            primary: "#ffc870",
            primaryText: "#3a2800",
            primaryContainer: "#a06820",
            primaryContainerText: "#ffe8c0",
            secondary: "#d4c8a4",
            secondaryContainer: "#4a4030",
            secondaryContainerText: "#e8dcbe",
            tertiary: "#c4d8ff",
            tertiaryContainer: "#3a4a70",
            tertiaryContainerText: "#d8e4ff",
            successColor: "#90d9a8",
            successContainer: "#1a4a30",
            warningColor: "#f0e06a",
            warningContainer: "#4a421a",
            errorColor: "#ffb0a0",
            errorContainer: "#6a2a24",
            outline: "#4a4030",
            outlineVariant: "#3a3020"
        },
        light: {
            background: "#fcf8f0",
            surface: "#fcf8f0",
            layer0: "#f8f0e0",
            layer1: "#f0e4c8",
            layer1Hover: "#e4d4a8",
            layer1Active: "#d0bc88",
            surfaceContainerLowest: "#ffffff",
            surfaceContainerLow: "#f8f0e0",
            surfaceContainer: "#f0e4c8",
            surfaceContainerHigh: "#e4d4a8",
            surfaceContainerHighest: "#d0bc88",
            text: "#1a1408",
            mutedText: "#4a3a1a",
            subtleText: "#6a5a3a",
            primary: "#a06820",
            primaryText: "#ffffff",
            primaryContainer: "#ffe8c0",
            primaryContainerText: "#3a2800",
            secondary: "#6a5a3a",
            secondaryContainer: "#e8dcbe",
            secondaryContainerText: "#1a1408",
            tertiary: "#3a4a9a",
            tertiaryContainer: "#d8e4ff",
            tertiaryContainerText: "#001a3a",
            successColor: "#1a7a3a",
            successContainer: "#c4f0d4",
            warningColor: "#8a7a1a",
            warningContainer: "#fef8d8",
            errorColor: "#b8382a",
            errorContainer: "#fad5d0",
            outline: "#b8a070",
            outlineVariant: "#d4c0a0"
        }
    },
    neutral: {
        dark: {
            background: "#121416",
            surface: "#121416",
            layer0: "#1a1d20",
            layer1: "#212528",
            layer1Hover: "#2a2f33",
            layer1Active: "#363c40",
            surfaceContainerLowest: "#0c0e0f",
            surfaceContainerLow: "#1a1d20",
            surfaceContainer: "#212528",
            surfaceContainerHigh: "#2a2f33",
            surfaceContainerHighest: "#363c40",
            text: "#dcdfe2",
            mutedText: "#a8acaf",
            subtleText: "#7a7e82",
            primary: "#c8c8c8",
            primaryText: "#1a1a1a",
            primaryContainer: "#404040",
            primaryContainerText: "#e0e0e0",
            secondary: "#b8b8b8",
            secondaryContainer: "#383838",
            secondaryContainerText: "#d0d0d0",
            tertiary: "#c0c0d0",
            tertiaryContainer: "#383848",
            tertiaryContainerText: "#d4d4e0",
            successColor: "#90c8a0",
            successContainer: "#1a4030",
            warningColor: "#e0d068",
            warningContainer: "#403a1a",
            errorColor: "#e8a0a0",
            errorContainer: "#5a2828",
            outline: "#3a3e42",
            outlineVariant: "#2a2e32"
        },
        light: {
            background: "#f6f7f8",
            surface: "#f6f7f8",
            layer0: "#eceef0",
            layer1: "#e0e3e6",
            layer1Hover: "#d0d4d8",
            layer1Active: "#b8bec4",
            surfaceContainerLowest: "#ffffff",
            surfaceContainerLow: "#eceef0",
            surfaceContainer: "#e0e3e6",
            surfaceContainerHigh: "#d0d4d8",
            surfaceContainerHighest: "#b8bec4",
            text: "#1a1d20",
            mutedText: "#4a4e52",
            subtleText: "#6a6e72",
            primary: "#5a5e62",
            primaryText: "#ffffff",
            primaryContainer: "#e0e0e0",
            primaryContainerText: "#1a1a1a",
            secondary: "#6a6e72",
            secondaryContainer: "#d0d0d0",
            secondaryContainerText: "#1a1d20",
            tertiary: "#5a5a72",
            tertiaryContainer: "#d4d4e0",
            tertiaryContainerText: "#1a1a30",
            successColor: "#2a7a4a",
            successContainer: "#c4e8d0",
            warningColor: "#8a7a1a",
            warningContainer: "#fef5d8",
            errorColor: "#b0382a",
            errorContainer: "#fad5d0",
            outline: "#aab0b6",
            outlineVariant: "#c8ced4"
        }
    }
};

var themeIds = ["default", "blue", "green", "rose", "amber", "neutral"];

function getPreset(themeId, isLight) {
    var preset = presets[themeId] || presets["default"];
    return isLight ? preset.light : preset.dark;
}

function applyAccent(palette, accentColor) {
    if (!accentColor || accentColor.length === 0)
        return palette;
    var result = Object.assign({}, palette);
    result.primary = accentColor;
    // Derive primaryText from luminance
    var c = Qt.color(accentColor);
    var luminance = 0.299 * c.r + 0.587 * c.g + 0.114 * c.b;
    result.primaryText = luminance > 0.5 ? "#1a1a1a" : "#ffffff";
    // Derive primaryContainer by darkening/lightening
    result.primaryContainer = Qt.lighter(accentColor, luminance > 0.5 ? 0.6 : 1.4);
    result.primaryContainerText = luminance > 0.5 ? "#ffffff" : "#1a1a1a";
    return result;
}