import QtQuick
import Quickshell
import Quickshell.Io

// NiriConfig — manages the niri layout fragment lifecycle.
// Handles: detecting include, backing up config.kdl, writing layout.kdl,
// inserting include, and triggering niri config reload.

Item {
    id: root

    // --- Paths ---
    readonly property string niriConfigDir: {
        var x = Quickshell.env("XDG_CONFIG_HOME");
        var h = Quickshell.env("HOME");
        var base = (x && x.length > 0) ? x : (h + "/.config");
        return base + "/niri";
    }
    readonly property string configKdlPath: niriConfigDir + "/config.kdl"
    readonly property string strataDir: niriConfigDir + "/strata"
    readonly property string layoutKdlPath: strataDir + "/layout.kdl"
    readonly property string backupPath: configKdlPath + ".strata-backup"

    // --- State ---
    readonly property bool includePresent: _includePresent
    readonly property bool fragmentExists: _fragmentExists
    readonly property string configContent: _configContent
    readonly property string fragmentPreview: _fragmentPreview
    readonly property string lastError: _lastError
    readonly property string lastStatus: _lastStatus

    property bool _includePresent: false
    property bool _fragmentExists: false
    property string _configContent: ""
    property string _fragmentPreview: ""
    property string _lastError: ""
    property string _lastStatus: ""

    // --- Check: read config.kdl and detect include ---
    function check() {
        _lastError = "";
        _lastStatus = "";
        configReader.path = configKdlPath;
    }

    // --- Setup: backup config.kdl, create strata dir, write fragment, insert include ---
    function setup(opts) {
        _lastError = "";
        _lastStatus = "";
        _fragmentPreview = generateFragment(opts);
        var cmd = "mkdir -p '" + strataDir + "' && printf '%s' '" + escapeShell(_fragmentPreview) + "' > '" + layoutKdlPath + "'";
        setupProcess.command = ["sh", "-c", cmd];
        setupProcess.running = true;
    }

    // --- Apply: regenerate fragment and reload niri config ---
    function apply(opts) {
        _lastError = "";
        _lastStatus = "";
        _fragmentPreview = generateFragment(opts);
        var cmd = "printf '%s' '" + escapeShell(_fragmentPreview) + "' > '" + layoutKdlPath + "'";
        applyProcess.command = ["sh", "-c", cmd];
        applyProcess.running = true;
    }

    // --- Helpers ---

    function generateFragment(opts) {
        var gapsVal = Math.max(0, Math.min(64, parseInt(opts.gaps) || 0));
        var centerMode;
        if (opts.preset === "center-column")
            centerMode = "always";
        else if (opts.preset === "left-column")
            centerMode = "never";
        else
            centerMode = "on-overflow";

        var ringEnabled = opts.focusRingEnabled !== false;
        var ringWidth = Math.max(0, Math.min(20, parseInt(opts.focusRingWidth) || 0));
        var cornerRadius = Math.max(0, Math.min(30, parseInt(opts.windowCornerRadius) || 0));
        var preferNoCsd = opts.preferNoCsd !== false;

        var frag = '// Generated by niri-strata Settings.\n' +
                   '// Edit Settings, not this file. Manual changes may be overwritten.\n' +
                   'layout {\n' +
                   '    gaps ' + gapsVal + '\n' +
                   '    center-focused-column "' + centerMode + '"\n';
        if (ringEnabled)
            frag += '    focus-ring {\n        width ' + ringWidth + '\n    }\n';
        else
            frag += '    focus-ring {\n        off\n    }\n';
        frag += '}\n';
        if (cornerRadius > 0)
            frag += 'window-rule {\n    geometry-corner-radius ' + cornerRadius + '\n    clip-to-geometry true\n}\n';
        if (preferNoCsd)
            frag += 'prefer-no-csd\n';
        return frag;
    }

    function escapeShell(text) {
        return String(text).replace(/'/g, "'\\''");
    }

    function detectIncludeInContent(content) {
        var text = String(content || "");
        if (text.length === 0)
            return false;
        var lines = text.split("\n");
        for (var i = 0; i < lines.length; i++) {
            var trimmed = lines[i].trim();
            if (trimmed.length === 0 || trimmed.startsWith("//"))
                continue;
            if (/^include\s+"strata\/layout\.kdl"/.test(trimmed))
                return true;
        }
        return false;
    }

    // --- File reader ---
    FileView {
        id: configReader
        path: root.configKdlPath
        onLoaded: {
            root._configContent = text();
            root._includePresent = root.detectIncludeInContent(root._configContent);
            fragmentChecker.command = ["test", "-f", root.layoutKdlPath];
            fragmentChecker.running = true;
        }
        onLoadFailed: {
            root._lastError = "Could not read config.kdl";
            root._configContent = "";
            root._includePresent = false;
        }
    }

    // Check if fragment file exists
    Process {
        id: fragmentChecker
        command: []
        onExited: (exitCode) => {
            root._fragmentExists = (exitCode === 0);
        }
    }

    // Setup: mkdir + write fragment → backup + insert include → validate → reload
    Process {
        id: setupProcess
        command: []
        onExited: (exitCode) => {
            if (exitCode !== 0) {
                root._lastError = "Failed to create strata directory or write layout.kdl";
                return;
            }
            var cmd = "cp '" + root.configKdlPath + "' '" + root.backupPath + "' && " +
                      "grep -q 'include \"strata/layout.kdl\"' '" + root.configKdlPath + "' || " +
                      "printf '\\ninclude \"strata/layout.kdl\"\\n' >> '" + root.configKdlPath + "'";
            backupProcess.command = ["sh", "-c", cmd];
            backupProcess.running = true;
        }
    }

    // Backup config.kdl + insert include
    Process {
        id: backupProcess
        command: []
        onExited: (exitCode) => {
            if (exitCode !== 0) {
                root._lastError = "Failed to backup config.kdl or insert include";
                return;
            }
            validateProcess.command = ["niri", "validate", "-c", root.configKdlPath];
            validateProcess.running = true;
        }
    }

    // Apply: write fragment → validate → reload
    Process {
        id: applyProcess
        command: []
        onExited: (exitCode) => {
            if (exitCode !== 0) {
                root._lastError = "Failed to write layout.kdl";
                return;
            }
            validateProcess.command = ["niri", "validate", "-c", root.configKdlPath];
            validateProcess.running = true;
        }
    }

    // Validate config
    Process {
        id: validateProcess
        command: []
        onExited: (exitCode) => {
            if (exitCode !== 0) {
                root._lastError = "niri validate failed. Backup at " + root.backupPath;
                root._lastStatus = "";
                return;
            }
            reloadProcess.command = ["niri", "msg", "action", "load-config-file"];
            reloadProcess.running = true;
        }
    }

    // Reload niri config
    Process {
        id: reloadProcess
        command: []
        onExited: (exitCode) => {
            if (exitCode !== 0) {
                root._lastError = "niri reload failed";
                root._lastStatus = "";
                return;
            }
            root._lastStatus = "Applied successfully";
            root._lastError = "";
            root._includePresent = true;
            root._fragmentExists = true;
            root.check();
        }
    }
}