import test from "node:test";
import assert from "node:assert/strict";

import {
  SETTINGS_SPEC,
  buildIncludeLine,
  coerceValue,
  defaultSettings,
  detectInclude,
  generateNiriFragment,
  insertInclude,
  mergeSettings,
  migrateSettings,
} from "./lib/settings-core.mjs";

const EXPECTED_DEFAULTS = {
  configVersion: 1,
  themeMode: "dark",
  themeId: "default",
  accentColor: "",
  barPosition: "top",
  barStyle: "flush",
  barShowBackground: true,
  barHeight: 34,
  barIconButtonSize: 26,
  barSideMargin: 10,
  barGroupSpacing: 8,
  barWingRadius: 8,
  barBottomRadius: 12,
  barFlattenOnMaximized: true,
  sidebarWidth: 440,
  sidebarWheelScrollFactor: 1.2,
  workspaceDragReorder: true,
  workspacePillHeight: 22,
  workspaceActiveWidth: 48,
  workspacePillSpacing: 4,
  workspaceAnimationDuration: 200,
  workspaceQuickAnimationDuration: 120,
  workspaceDragPreviewDuration: 90,
  notificationMaxHistoryCount: 500,
  notificationMaxHistoryPerApp: 200,
  notificationPreviewCount: 2,
  notificationExpandedPreviewCount: 8,
  recordingSaveDir: "",
  recordingDefaultMode: "output",
  recordingAudioEnabled: false,
  screenshotDefaultAction: "copy",
  niriLayoutManaged: false,
  niriLayoutGaps: 8,
  niriLayoutPreset: "center-column",
  niriFocusRingEnabled: true,
  niriFocusRingWidth: 4,
  niriWindowCornerRadius: 0,
  niriPreferNoCsd: true,
  motionSpeed: "normal",
  autoMode: "time",
  autoTimeStart: "18:00",
  autoTimeEnd: "06:00",
  autoLat: 0.0,
  autoLng: 0.0,
  wallpaperPath: "",
  systemThemeEnabled: false,
  systemThemeGtkEnabled: true,
  systemThemeQtEnabled: true,
  systemThemeApplyOnModeChange: true,
};
test("defaultSettings returns all 49 spec keys with their defaults", () => {
  assert.deepEqual(defaultSettings(), EXPECTED_DEFAULTS);
});

test("coerceValue coerces string ints to numbers and string bools to booleans", () => {
  assert.equal(coerceValue("barHeight", "42").value, 42);
  assert.equal(coerceValue("barShowBackground", "true").value, true);
});

test("coerceValue clamps out-of-range numbers to min/max bounds", () => {
  assert.equal(coerceValue("barHeight", 999).value, 60);
  assert.equal(coerceValue("barHeight", -5).value, 28);
  assert.equal(coerceValue("sidebarWheelScrollFactor", 999).value, 5.0);
});

test("coerceValue falls back to default for invalid enum, keeps valid enum", () => {
  assert.deepEqual(coerceValue("barPosition", "invalid"), { value: "top", ok: false });
  assert.deepEqual(coerceValue("barPosition", "bottom"), { value: "bottom", ok: true });
});

test("coerceValue validates accentColor regex, rejecting non-hex", () => {
  assert.deepEqual(coerceValue("accentColor", "#ff0000"), { value: "#ff0000", ok: true });
  assert.deepEqual(coerceValue("accentColor", "red"), { value: "", ok: false });
});

test("mergeSettings keeps known keys and drops unknown keys", () => {
  const merged = mergeSettings({ barHeight: 40, fooBar: 123 });
  assert.equal(merged.barHeight, 40);
  assert.equal(Object.hasOwn(merged, "fooBar"), false);
});

test("migrateSettings fills missing keys with defaults from a v0 fragment", () => {
  const migrated = migrateSettings({ configVersion: 0, themeMode: "light" }, 0);
  assert.equal(Object.keys(migrated).length, 49);
  assert.equal(migrated.themeMode, "light");
  assert.equal(migrated.barHeight, 34);
});

test("mergeSettings returns defaults for non-object input without throwing", () => {
  assert.deepEqual(mergeSettings(null), EXPECTED_DEFAULTS);
  assert.deepEqual(mergeSettings("str"), EXPECTED_DEFAULTS);
  assert.deepEqual(mergeSettings(42), EXPECTED_DEFAULTS);
});

test("generateNiriFragment emits valid KDL with all managed keys", () => {
  const fragment = generateNiriFragment({
    gaps: 8, preset: "center-column",
    focusRingEnabled: true, focusRingWidth: 4,
    windowCornerRadius: 12, preferNoCsd: true
  });
  assert.ok(fragment.startsWith("// Generated by niri-strata Settings."));
  assert.ok(fragment.includes("gaps 8"));
  assert.ok(fragment.includes("center-focused-column"));
  assert.ok(fragment.includes("focus-ring"));
  assert.ok(fragment.includes("width 4"));
  assert.ok(fragment.includes("geometry-corner-radius 12"));
  assert.ok(fragment.includes("prefer-no-csd"));
});

test("generateNiriFragment disables focus-ring when requested", () => {
  const fragment = generateNiriFragment({
    gaps: 8, preset: "center-column",
    focusRingEnabled: false, focusRingWidth: 4,
    windowCornerRadius: 0, preferNoCsd: false
  });
  assert.ok(fragment.includes("focus-ring"));
  assert.ok(fragment.includes("off"));
  assert.ok(!fragment.includes("prefer-no-csd"));
  assert.ok(!fragment.includes("geometry-corner-radius"));
});

test("detectInclude recognizes the strata layout include only", () => {
  assert.equal(detectInclude('include "strata/layout.kdl"'), true);
  assert.equal(detectInclude('include "other.kdl"'), false);
});

test("insertInclude adds include line only when missing", () => {
  const result1 = insertInclude('some config\n');
  assert.ok(result1.inserted);
  assert.ok(result1.content.includes('include "strata/layout.kdl"'));

  const result2 = insertInclude('include "strata/layout.kdl"\n');
  assert.ok(!result2.inserted);
});