import test from "node:test";
import assert from "node:assert/strict";

import {
  renderGtk,
  renderQt,
  snapshotPalette,
  insertGtk4Import,
  gtk4ImportBlock,
  GTK4_IMPORT_MARKER_START,
  GTK4_IMPORT_MARKER_END,
} from "../scripts/theme-render.mjs";

// ── Test palette ──

const TEST_PALETTE = {
  background: "#101418",
  surface: "#101418",
  layer0: "#0b0f12",
  layer1: "#171c20",
  layer1Hover: "#1d2328",
  layer1Active: "#273038",
  surfaceContainerLowest: "#0b0f12",
  surfaceContainerLow: "#171c20",
  surfaceContainer: "#1d2328",
  surfaceContainerHigh: "#273038",
  surfaceContainerHighest: "#323c45",
  text: "#e2e8ee",
  mutedText: "#bcc7d0",
  subtleText: "#89959f",
  primary: "#9bd4ff",
  primaryText: "#00344f",
  primaryContainer: "#164b68",
  primaryContainerText: "#cce7ff",
  secondary: "#c0c8d2",
  secondaryContainer: "#3f4850",
  secondaryContainerText: "#dce4ec",
  tertiary: "#dbc0ff",
  tertiaryContainer: "#55406f",
  tertiaryContainerText: "#eddcff",
  successColor: "#9ed9b3",
  successContainer: "#1f5234",
  warningColor: "#f3cf7a",
  warningContainer: "#5a471b",
  errorColor: "#ffb4ab",
  errorContainer: "#73342d",
  outline: "#414b54",
  outlineVariant: "#303941",
};

// ── 1. snapshotPalette ──

test("snapshotPalette fills missing fields with #000000", () => {
  const partial = { primary: "#fff", surface: "#000" };
  const snap = snapshotPalette(partial);
  assert.equal(snap.primary, "#fff");
  assert.equal(snap.surface, "#000");
  assert.equal(snap.text, "#000000");
  assert.equal(snap.errorColor, "#000000");
});

// ── 2. GTK CSS rendering ──

test("renderGtk produces valid CSS with @define-color directives", () => {
  const css = renderGtk(TEST_PALETTE);
  assert.match(css, /\/\* Generated by niri-strata Settings/);
  assert.match(css, /@define-color accent_bg_color #9bd4ff;/);
  assert.match(css, /@define-color window_bg_color #101418;/);
  assert.match(css, /@define-color window_fg_color #e2e8ee;/);
  assert.match(css, /@define-color headerbar_bg_color #1d2328;/);
});

test("renderGtk includes error and success color definitions", () => {
  const css = renderGtk(TEST_PALETTE);
  assert.match(css, /@define-color error_bg_color #ffb4ab;/);
  assert.match(css, /@define-color success_bg_color #9ed9b3;/);
  assert.match(css, /@define-color destructive_bg_color #ffb4ab;/);
});

test("renderGtk includes border and shade colors", () => {
  const css = renderGtk(TEST_PALETTE);
  assert.match(css, /@define-color border_color #303941;/);
  assert.match(css, /@define-color shade_color #414b54;/);
});

test("renderGtk ends with niri-strata marker", () => {
  const css = renderGtk(TEST_PALETTE);
  assert.match(css, /\/\* End of niri-strata generated colors \*\//);
});

// ── 3. Qt color scheme rendering ──

test("renderQt produces a valid KDE color scheme with [Color Scheme] header", () => {
  const scheme = renderQt(TEST_PALETTE);
  assert.match(scheme, /\[Color Scheme\]/);
  assert.match(scheme, /Name=NiriStrata/);
  assert.match(scheme, /Comment=Generated by niri-strata Settings/);
});

test("renderQt maps primary to highlightColor and linkColor", () => {
  const scheme = renderQt(TEST_PALETTE);
  assert.match(scheme, /highlightColor=#9bd4ff/);
  assert.match(scheme, /highlightedTextColor=#00344f/);
  assert.match(scheme, /linkColor=#9bd4ff/);
});

test("renderQt includes [Colors:Selection] with primary as background", () => {
  const scheme = renderQt(TEST_PALETTE);
  assert.match(scheme, /\[Colors:Selection\]/);
  assert.match(scheme, /Background=#9bd4ff/);
  assert.match(scheme, /Foreground=#00344f/);
});

test("renderQt includes [Colors:View] and [Colors:Window] sections", () => {
  const scheme = renderQt(TEST_PALETTE);
  assert.match(scheme, /\[Colors:View\]/);
  assert.match(scheme, /\[Colors:Window\]/);
  assert.match(scheme, /\[Colors:Button\]/);
  assert.match(scheme, /\[Colors:Tooltip\]/);
});

// ── 4. GTK4 import block ──

test("gtk4ImportBlock contains markers and @import line", () => {
  const block = gtk4ImportBlock();
  assert.match(block, /niri-strata-import-start/);
  assert.match(block, /niri-strata-import-end/);
  assert.match(block, /@import url\("niri-strata-colors\.css"\);/);
});

test("insertGtk4Import prepends import block to empty content", () => {
  const result = insertGtk4Import("");
  assert.match(result, /niri-strata-import-start/);
  assert.match(result, /@import url\("niri-strata-colors\.css"\);/);
  assert.match(result, /niri-strata-import-end/);
});

test("insertGtk4Import is idempotent — running twice produces same output", () => {
  const existing = "/* user content */\n@define-color foo #fff;\n";
  const first = insertGtk4Import(existing);
  const second = insertGtk4Import(first);
  assert.equal(first, second, "idempotent: second run should not duplicate or change");
});

test("insertGtk4Import preserves existing user content", () => {
  const existing = "/* my custom css */\n.button { color: red; }\n";
  const result = insertGtk4Import(existing);
  assert.match(result, /\/\* my custom css \*\//);
  assert.match(result, /\.button \{ color: red; \}/);
});

test("insertGtk4Import replaces existing marker block, not appends", () => {
  const old = "/* niri-strata-import-start */\n@import url(\"old.css\");\n/* niri-strata-import-end */\nbody { }";
  const result = insertGtk4Import(old);
  // Should have exactly one import block
  const count = (result.match(/niri-strata-import-start/g) || []).length;
  assert.equal(count, 1, "should have exactly one marker block");
  assert.match(result, /@import url\("niri-strata-colors\.css"\);/);
  assert.doesNotMatch(result, /old\.css/);
  assert.match(result, /body \{ \}/);
});

// ── 5. Portal/gsettings command ──

import { portalCommand, portalDconfCommand, renderNiri } from "../scripts/theme-render.mjs";

test("portalCommand returns gsettings set for prefer-dark when isLight=false", () => {
  const cmd = portalCommand(false);
  assert.deepEqual(cmd, ["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", "prefer-dark"]);
});

test("portalCommand returns gsettings set for prefer-light when isLight=true", () => {
  const cmd = portalCommand(true);
  assert.deepEqual(cmd, ["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", "prefer-light"]);
});

test("portalDconfCommand returns dconf write for dark mode", () => {
  const cmd = portalDconfCommand(false);
  assert.deepEqual(cmd, ["dconf", "write", "/org/gnome/desktop/interface/color-scheme", "'prefer-dark'"]);
});

// ── 6. niri colors.kdl rendering ──

test("renderNiri produces valid KDL with environment block", () => {
  const kdl = renderNiri(TEST_PALETTE);
  assert.match(kdl, /Generated by niri-strata Settings/);
  assert.match(kdl, /environment \{/);
  assert.match(kdl, /GTK_THEME/);
  assert.match(kdl, /End of niri-strata generated colors/);
});