// Pure Node ESM renderer: generates external theme files from a palette JSON.
// No QML deps. Testable without launching Quickshell.
//
// Input: palette JSON snapshot (the same shape as ThemePresets presets)
//   { dark: { primary: "#9bd4ff", surface: "#101418", ... }, light: { ... } }
//
// Targets:
//   gtk    → GTK CSS file with @define-color directives
//   qt     → KDE color scheme file (.colors format)
//
// Usage from harness:
//   import { renderGtk, renderQt, renderPaletteSnapshot } from "./theme-render.mjs";

// ── palette snapshot ─────────────────────────────────────────────

/**
 * Build a palette JSON snapshot from Theme.colors-style input.
 * Takes an object of camelCase color names → hex values and normalizes
 * it to the full 32-field shape expected by renderers.
 *
 * @param {Object} colors - { primary: "#9bd4ff", surface: "#101418", ... }
 * @returns {Object} normalized palette with all 32 fields
 */
export function snapshotPalette(colors) {
  const REQUIRED = [
    "background", "surface", "layer0", "layer1", "layer1Hover", "layer1Active",
    "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
    "surfaceContainerHigh", "surfaceContainerHighest",
    "text", "mutedText", "subtleText",
    "primary", "primaryText", "primaryContainer", "primaryContainerText",
    "secondary", "secondaryContainer", "secondaryContainerText",
    "tertiary", "tertiaryContainer", "tertiaryContainerText",
    "successColor", "successContainer",
    "warningColor", "warningContainer",
    "errorColor", "errorContainer",
    "outline", "outlineVariant",
  ];

  const out = {};
  for (const field of REQUIRED) {
    out[field] = colors[field] || "#000000";
  }
  return out;
}

// ── GTK CSS renderer ─────────────────────────────────────────────

/**
 * Render GTK CSS from a palette snapshot.
 * Uses @define-color directives that GTK3/GTK4 themes (adw-gtk3, etc.) consume.
 *
 * @param {Object} palette - palette snapshot (from snapshotPalette)
 * @returns {string} CSS content with @define-color directives
 */
export function renderGtk(palette) {
  const lines = [
    "/* Generated by niri-strata Settings. Do not edit manually. */",
    "/* This file is managed by niri-strata and may be overwritten. */",
    "",
    "@define-color accent_bg_color " + palette.primary + ";",
    "@define-color accent_fg_color " + palette.primaryText + ";",
    "@define-color window_bg_color " + palette.background + ";",
    "@define-color window_fg_color " + palette.text + ";",
    "@define-color view_bg_color " + palette.surface + ";",
    "@define-color view_fg_color " + palette.text + ";",
    "@define-color headerbar_bg_color " + palette.surfaceContainer + ";",
    "@define-color headerbar_fg_color " + palette.text + ";",
    "@define-color sidebar_bg_color " + palette.surfaceContainer + ";",
    "@define-color sidebar_fg_color " + palette.text + ";",
    "@define-color secondary_sidebar_bg_color " + palette.surfaceContainerLow + ";",
    "@define-color secondary_sidebar_fg_color " + palette.text + ";",
    "",
    "@define-color destructive_bg_color " + palette.errorColor + ";",
    "@define-color destructive_fg_color " + palette.text + ";",
    "@define-color error_bg_color " + palette.errorColor + ";",
    "@define-color error_fg_color " + palette.text + ";",
    "@define-color success_bg_color " + palette.successColor + ";",
    "@define-color success_fg_color " + palette.text + ";",
    "@define-color warning_bg_color " + palette.warningColor + ";",
    "@define-color warning_fg_color " + palette.text + ";",
    "",
    "@define-color card_bg_color " + palette.surfaceContainer + ";",
    "@define-color card_fg_color " + palette.text + ";",
    "@define-color popover_bg_color " + palette.surfaceContainerHigh + ";",
    "@define-color popover_fg_color " + palette.text + ";",
    "",
    "@define-color dialog_bg_color " + palette.surfaceContainerHigh + ";",
    "@define-color dialog_fg_color " + palette.text + ";",
    "",
    "@define-color border_color " + palette.outlineVariant + ";",
    "@define-color shade_color " + palette.outline + ";",
    "",
    "/* End of niri-strata generated colors */",
  ];

  return lines.join("\n") + "\n";
}

// ── Qt color scheme renderer ──────────────────────────────────────

/**
 * Render a KDE color scheme (.colors) file from a palette snapshot.
 * This format is used by qt5ct and qt6ct when custom_palette=true.
 *
 * @param {Object} palette - palette snapshot
 * @returns {string} .colors file content (INI format)
 */
export function renderQt(palette) {
  const lines = [
    "[Color Scheme]",
    "Name=NiriStrata",
    "Comment=Generated by niri-strata Settings",
    "",
    "[WM]",
    "activeBackground=" + palette.surface,
    "activeForeground=" + palette.text,
    "inactiveBackground=" + palette.surfaceContainer,
    "inactiveForeground=" + palette.mutedText,
    "",
    "[General]",
    "windowBackground=" + palette.background,
    "windowForeground=" + palette.text,
    "baseColor=" + palette.surfaceContainerLow,
    "alternateBaseColor=" + palette.surfaceContainer,
    "textColor=" + palette.text,
    "buttonColor=" + palette.surfaceContainerHigh,
    "buttonBackgroundColor=" + palette.surfaceContainer,
    "buttonTextColor=" + palette.text,
    "highlightColor=" + palette.primary,
    "highlightedTextColor=" + palette.primaryText,
    "linkColor=" + palette.primary,
    "visitedLinkColor=" + palette.tertiary,
    "",
    "[Selection]",
    "background=" + palette.primary,
    "foreground=" + palette.primaryText,
    "",
    "[KDE]",
    "contrast=4",
    "",
    "[Colors:View]",
    "Background=" + palette.surface,
    "Foreground=" + palette.text,
    "BackgroundAlternate=" + palette.surfaceContainerLow,
    "BackgroundNormal=" + palette.surface,
    "ForegroundLink=" + palette.primary,
    "ForegroundVisited=" + palette.tertiary,
    "",
    "[Colors:Window]",
    "Background=" + palette.surfaceContainer,
    "Foreground=" + palette.text,
    "BackgroundNormal=" + palette.surfaceContainer,
    "ForegroundNormal=" + palette.text,
    "",
    "[Colors:Button]",
    "Background=" + palette.surfaceContainerHigh,
    "Foreground=" + palette.text,
    "BackgroundNormal=" + palette.surfaceContainerHigh,
    "ForegroundNormal=" + palette.text,
    "",
    "[Colors:Selection]",
    "Background=" + palette.primary,
    "Foreground=" + palette.primaryText,
    "BackgroundNormal=" + palette.primary,
    "ForegroundNormal=" + palette.primaryText,
    "",
    "[Colors:Tooltip]",
    "Background=" + palette.surfaceContainerHigh,
    "Foreground=" + palette.text,
    "",
    "[Colors:Complementary]",
    "Background=" + palette.surfaceContainer,
    "Foreground=" + palette.text,
    "",
    "/* End of niri-strata generated color scheme */",
  ];

  return lines.join("\n") + "\n";
}

// ── GTK import line for GTK4 ─────────────────────────────────────

/**
 * Generate the @import line that should be injected into gtk-4.0/gtk.css.
 * Uses a marker block so re-runs are idempotent.
 */
export const GTK4_IMPORT_MARKER_START = "/* niri-strata-import-start */";
export const GTK4_IMPORT_MARKER_END = "/* niri-strata-import-end */";

export function gtk4ImportBlock() {
  return GTK4_IMPORT_MARKER_START + "\n" +
    '@import url("niri-strata-colors.css");\n' +
    GTK4_IMPORT_MARKER_END;
}

/**
 * Insert the GTK4 import block into existing gtk.css content.
 * If the marker already exists, replace the old block.
 * If not, prepend the import block at the top.
 * Idempotent: running twice produces the same output.
 */
export function insertGtk4Import(existingContent) {
  const block = gtk4ImportBlock();
  const text = String(existingContent || "");

  // Check for existing marker
  const startIdx = text.indexOf(GTK4_IMPORT_MARKER_START);
  if (startIdx >= 0) {
    const endIdx = text.indexOf(GTK4_IMPORT_MARKER_END);
    if (endIdx >= 0) {
      // Replace existing block
      return text.slice(0, startIdx) + block + text.slice(endIdx + GTK4_IMPORT_MARKER_END.length);
    }
  }

  // Prepend
  return block + "\n" + text;
}